ALTER SESSION SET CONTAINER = ORCLPDB1;

CREATE USER dbzuser IDENTIFIED BY debezium
  DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION          TO dbzuser;
GRANT LOGMINING               TO dbzuser;
GRANT SELECT ANY TABLE        TO dbzuser;
GRANT SELECT ANY DICTIONARY   TO dbzuser;
GRANT SELECT ANY TRANSACTION  TO dbzuser;
GRANT LOCK ANY TABLE          TO dbzuser;
GRANT EXECUTE_CATALOG_ROLE    TO dbzuser;
GRANT SELECT_CATALOG_ROLE     TO dbzuser;
GRANT FLASHBACK ANY TABLE     TO dbzuser;

GRANT SELECT ON V_$DATABASE           TO dbzuser;
GRANT SELECT ON V_$ARCHIVED_LOG       TO dbzuser;
GRANT SELECT ON V_$LOG                TO dbzuser;
GRANT SELECT ON V_$LOGFILE            TO dbzuser;
GRANT SELECT ON V_$INSTANCE           TO dbzuser;
GRANT SELECT ON V_$TRANSACTION        TO dbzuser;
GRANT SELECT ON V_$LOGMNR_LOGS        TO dbzuser;
GRANT SELECT ON V_$LOGMNR_CONTENTS    TO dbzuser;
GRANT SELECT ON V_$LOGMNR_PARAMETERS  TO dbzuser;

EXIT;
